name: PEP8 Code Style Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4  # Actualizado a la versión v4

      - name: Set up Python
        uses: actions/setup-python@v5  # Actualizado a la versión v5
        with:
          python-version: '3.x'

      - name: Install Pylint
        run: pip install pylint

      - name: Run Pylint
        run: pylint **/*.py --exit-zero